# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(520, 395)
        self.btn_send = QtWidgets.QPushButton(Dialog)
        self.btn_send.setGeometry(QtCore.QRect(10, 350, 93, 28))
        self.btn_send.setObjectName("btn_send")
        self.btn_conn = QtWidgets.QPushButton(Dialog)
        self.btn_conn.setGeometry(QtCore.QRect(420, 10, 93, 28))
        self.btn_conn.setObjectName("btn_conn")
        self.textEdit_input = QtWidgets.QTextEdit(Dialog)
        self.textEdit_input.setGeometry(QtCore.QRect(10, 270, 501, 71))
        self.textEdit_input.setObjectName("textEdit_input")
        self.textEdit_content = QtWidgets.QTextEdit(Dialog)
        self.textEdit_content.setGeometry(QtCore.QRect(10, 50, 501, 211))
        self.textEdit_content.setObjectName("textEdit_content")
        self.comboBox_ports = QtWidgets.QComboBox(Dialog)
        self.comboBox_ports.setGeometry(QtCore.QRect(10, 10, 401, 22))
        self.comboBox_ports.setObjectName("comboBox_ports")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_send.setText(_translate("Dialog", "Send"))
        self.btn_conn.setText(_translate("Dialog", "Connect"))
